### ISSUE TITLE
Can we get version 1 as well?

### ISSUE THREAD

**Issue by leafac** [RecuencoJones/caddy-npm#1]
This project is an awesome idea!

**Comment by RecuencoJones** [comment]
Hi @leafac, I definitely wouldn't mind publishing v1 of caddy as well 😊

**Comment by RecuencoJones** [comment]
Versions 1.0.0 to 1.0.4 published under `previous` dist-tag!

**Comment by leafac** [comment]
Thank you!

I really like this project. It’s the [first in my dependency list](https://github.com/leafac/www.kill-the-newsletter.com/blob/master/package.json#L7). I mean, the list is alphabetical, but you get the idea 😃

**Comment by RecuencoJones** [comment]
Love it! That's a great usage example, thanks for sharing!
